e_0 = 1.602e-19             # elementary charge
N_A = 6.022e23              # Avogadro's number
k_B = 1.38e-23              # Boltzmann's constant
T = 298                     # temperature, K
z = 1                       # ion valency
beta = 1/k_B/T              # inverse thermal energy
eps_0 = 8.8541878128e-12    # vacuum permittivity, F/m
eps_r_water = 78.5          # relative permittivity of bulk water
c_water_bulk = 55.5 * 1e3   # water bulk concentration (density/molar mass), mol/m^3
